#![forbid(unsafe_code)]
#![cfg_attr(docsrs, feature(doc_cfg))]
#![doc = include_str!("./README.md")]

pub mod json {
    //! Includes files generated by `prost`.

    pub mod schema {
        //! Includes files generated by `prost`.
        //! Built from `jsonschema.proto`.

        include!("./generated/rt.json.schema.rs");
    }

    pub mod value {
        //! Includes files generated by `prost`.
        //! Built from `jsonvalue.proto`.

        include!("./generated/rt.json.value.rs");
    }
}

pub mod instance {
    //! Includes files generated by `prost`.
    //! Built from `instance.proto`.

    include!("./generated/rt.instance.rs");
}

pub mod registry {
    //! Includes files generated by `prost`.
    //! Built from `registry.proto`.

    include!("./generated/rt.registry.rs");
}

pub mod entity {
    //! Includes files generated by `prost`.
    //! Built from `entity.proto`.

    include!("./generated/rt.entity.rs");
}

pub mod request {
    //! Includes files generated by `prost`.
    //! Built from `request.proto`.

    include!("./generated/rt.request.rs");
}

pub mod response {
    //! Includes files generated by `prost`.
    //! Built from `response.proto`.

    include!("./generated/rt.response.rs");
}
