#![forbid(unsafe_code)]
#![cfg_attr(docsrs, feature(doc_cfg))]
#![doc = include_str!("./README.md")]

//! ### Examples
//!
//! ```rust
//! fn main() {}
//! ```

pub mod instance {
    //! Includes files generated by `prost`.
    //! Built from `instance.proto`.

    include!("./generated/instance.rs");
}

pub mod registry {
    //! Includes files generated by `prost`.
    //! Built from `registry.proto`.

    include!("./generated/registry.rs");
}
