#![forbid(unsafe_code)]
#![cfg_attr(docsrs, feature(doc_cfg))]
#![doc = include_str!("./README.md")]

pub mod policy {
    //! Includes files generated by `prost`.

    pub mod retry {
        //! Includes files generated by `prost`.
        //! Built from `policy/retry.proto`.

        tonic::include_proto!("rt.policy.retry");
    }

    pub mod timeout {
        //! Includes files generated by `prost`.
        //! Built from `policy/timeout.proto`.

        tonic::include_proto!("rt.policy.timeout");
    }
}

pub mod internal {
    //! Includes files generated by `prost`.

    pub mod json {
        //! Includes files generated by `prost`.
        //! Built from `internal/json.proto`.

        tonic::include_proto!("rt.internal.json");
    }
}

pub mod instance {
    //! Includes files generated by `prost`.
    //! Built from `instance.proto`.

    tonic::include_proto!("rt.instance");
}

pub mod registry {
    //! Includes files generated by `prost`.
    //! Built from `registry.proto`.

    tonic::include_proto!("rt.registry");
}

pub mod entity {
    //! Includes files generated by `prost`.
    //! Built from `entity.proto`.

    tonic::include_proto!("rt.entity");
}

pub mod request {
    //! Includes files generated by `prost`.
    //! Built from `request.proto`.

    tonic::include_proto!("rt.request");
}

pub mod response {
    //! Includes files generated by `prost`.
    //! Built from `response.proto`.

    tonic::include_proto!("rt.response");
}
